# Generated by Django 5.2.6 on 2025-09-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identifiant unique pour l'URL, ex: 'a-propos', 'notre-histoire'", unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
