# Generated by Django 5.2.6 on 2025-09-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order_in_menu']},
        ),
        migrations.AddField(
            model_name='page',
            name='order_in_menu',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le menu (le plus petit en premier)."),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='Cocher pour afficher cette page dans le menu principal.'),
        ),
    ]
