# Generated by Django 5.2.6 on 2025-09-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_page_order_in_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default="À Propos de l'École Téléma Ngenga", max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='pages_photos/')),
            ],
            options={
                'verbose_name': 'Page À Propos',
            },
        ),
        migrations.CreateModel(
            name='NotreHistoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Notre Histoire', max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='pages_photos/')),
            ],
            options={
                'verbose_name': 'Page Notre Histoire',
            },
        ),
        migrations.CreateModel(
            name='NotreMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Notre Mission', max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='pages_photos/')),
            ],
            options={
                'verbose_name': 'Page Notre Mission',
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
