# Generated by Django 5.2.6 on 2025-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('categorie', models.CharField(choices=[('terrain', 'Sur le terrain'), ('coulisses', 'Dans les coulisses')], max_length=20)),
            ],
        ),
    ]
